### ISSUE TITLE
unable to save jukebox.js in sub-directory

### ISSUE THREAD

**Issue by bghvdhout** [lukx/home-assistant-jukebox#1]
Hi,

Great work on this custom-card! Just installed it and it works when I follow your instructions.
However all my custom Lovelace cards are in /www/custom-lovelace/
When I put the jukebox.js in this folder, the card doesn't load. 
"custom element doesn't exist: jukebox-card"

resources:
  - url: /local/custom-lovelace/jukebox.js
    type: module

Also : does this script support adding version info, to avoid caching issues?

resources:
  - url: /local/custom-lovelace/jukebox.js?v=1  ??  Does this work
    type: module

Cheers,

Bram

**Comment by lukx** [comment]
I assume this is now irrelevant, right?
