### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Sonusss** [lukx/home-assistant-jukebox#3]
I tried to install your app but got the following error.
Custom element doesn't exist: jukebox-card.
I guess there is a missing file....

**Comment by cromatox** [comment]
You have to add the following ressource object in your .storage/lovelace configuration file:

```
{
    "data": {
        "config": {
            "resources": [
                {
                    "type": "module",
                    "url": "/local/jukebox.js"
                }
            ], 
            ...
        }
    }
}
```

**Comment by Sonusss** [comment]
Now I got this in lovelace

> You need to define your media player entities
> {
>   "type": "custom:jukebox-card"
> }

But player are supposed to be defined in ui-lovelace.yaml

>     entities:
>       - media_player.Cuisine
>       - media_player.Salon

My media players platform  is linkplay, might this be the problem ?
