### ISSUE TITLE
Volume slide

### ISSUE THREAD

**Issue by jvbragt** [lukx/home-assistant-jukebox#9]
Hi,

Somehow since yesterday the volume slider is gone. Only mute and stop is visable

**Comment by Geronimo2015** [comment]
Same here, slider, mute and stop button are gone, some update of HA broke style

**Comment by KarolKsionek** [comment]
+1

**Comment by lukx** [comment]
Fixed apparently, can anyone update and confirm please? @jvbragt ?

**Comment by jvbragt** [comment]
Sorry, updated the code restarted the HA and I don't see the volume slider.

**Comment by Geronimo2015** [comment]
> Fixed apparently, can anyone update and confirm please? @jvbragt ?

For me slider is back.

You have to hard refresh your browser with CTRL-F5

**Comment by jvbragt** [comment]
Sorry, For me it isn't.
